### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by whlowe** [jumbojett/Wordpress-OpenID-Connect-Login#3]
I tried to install the plugin but it could not be activated. It throws an error (screenshot below), which apparently means that it lacks some file.

![oidc-wordpress](https://cloud.githubusercontent.com/assets/5271048/4024034/26a14c26-2bb4-11e4-8b0b-2574c94f88f8.png)

**Comment by jumbojett** [comment]
Hi @willow9886, You are downloading the "zip file." You'll need to follow the instructions in the README. The issue is that Github does not support to have the submodules included when clicking the ZIP-Button. We are working on something for this - maybe getting rid of the submodules. You may alternatively you can download the dependency directly. Feel free to comment if you have any more questions.
